### ISSUE TITLE
virtual dependencies

### ISSUE THREAD

**Issue by darachg** [scalability-llnl/spack#11]
Hi,

This is a question about how virtual dependencies work.  On the develop branch, if run:

$ spack providers mpe
mpe2

... as expected. 

If I then (arbitrarily) edit var/spack/packages/zlib/package.py and insert

"provides('mpe')"

(I know zlib doesn't do this)

and then run:

$ spack providers mpe
    zlib

but there's now no mention of 'mpe2'.

Is this as intended?  Should I be adding more detailed version information to the virtual deps?

This is just a test example -- the case I'm thinking of is that, say, blas could be provided by atlas, openblas, mkl, acml,

Darach

**Comment by tgamblin** [comment]
Ack!  That's a bug -- your understanding is correct.  You should see zlib and mpe2 when you do this.

I'll need to update the way the ProviderIndex is stored in virtual.py.  It handles MPI fine because all the MPI implementations are providing different versions of the same virtual package, but it is screwing up the case where multiple packages provide the *same* version.  I should write some better tests for this as well.

**Comment by tgamblin** [comment]
@darachg Ok, I checked in a fix for this.  See the new branch above.  Can you try this version out?

**Comment by darachg** [comment]
Hi,

looks good -- multiple providers are now being listed

**Comment by tgamblin** [comment]
Thanks.  This is now in develop.
