### ISSUE TITLE
gcc package - needs to bootstrap libc/libstdc++

### ISSUE THREAD

**Issue by trws** [scalability-llnl/spack#203]
The gcc package currently depends on the system libstdc++ to bootstrap rather than building its own.  Certain systems with incredibly ancient versions of libstdc++, which will remain nameless to protect the guilty, can't build the gcc 5.2 version because of this behavior.  Probably the best way to fix this is to rework the process to bootstrap gcc completely from scratch, but I'm not sure whether this is best done as a rework of the gcc package itself, or a split into a libc, libstdc++ and gcc packages.  The latter seems to make more sense on the surface, but because of the cycle of rebuilds required the former might be the only way to do it without leaving partial bootstrap versions around.

**Comment by tgamblin** [comment]
I *think* I like the former better, just because I don't see the need to have the extra libc and libstdc++ packages sitting around in separate directories.  I'm also hesitant to mess with the way gcc lays things out -- that seems like something a lot of things will assume.  @mplegendre: any opinions?

**Comment by mplegendre** [comment]
I'm confused.  From looking at the gcc package.py, I'd think that it was 
already bootstrapping itself.  I thought you explicitly had to add a 
--disable-bootstrap to gcc for it to not do so.

Also, I don't think libstdc++.so is distributed seperate from gcc.  I 
don't think it's possible to make it a seperate package anymore.

We should avoid getting into the business of building building libc, which 
is a seperate package from libstdc++ anyways.

-Matt

**Comment by trws** [comment]
It is bootstrapping itself, as you point out that's what it basically always does, but it doesn't bootstrap libstdc++ when a system version is available, or so it seems at least.  The current gcc 5.2 package for example dies trying to use the system libstdc++ during its build.  The main point was to build a minimal libstdc++ in-tree first, then use that to build the full gcc and libstdc++ afterward.

**Comment by mplegendre** [comment]
I reproduced the issue, but didn't yet narrow down on the root cause.  The bootstrapping xgcc is searching for its own libstdc++.so, but not in the directories where it actually exists.  Perhaps the various directory overrides in package.py are throwing it off.  Perhaps something else went wrong and libstdc++.so wasn't copied to the right place.

**Comment by trws** [comment]
Interesting, we may have actually gotten slightly different issues.  When I tried it, xgcc died before the in-tree libstdc++ was built at all, maybe something in my environment messed with it?

**Comment by sjtbham** [comment]
I mentioned this on the mailing list and was pointed over here. On my build gcc was dying. On one of the test systems I built on, its a pretty cut down install with very little else in the environment, so don't think its a messed up environment.

**Comment by mplegendre** [comment]
I just submitted this pull request, https://github.com/scalability-llnl/spack/pull/222 to fix the issue.  Could someone else verify this works for them?

The problem came from us passing our rpath options to gcc's configure via --with-stage1-ldflags and --with-boot-ldflags.  GCC has default values of "-static-libstdc++ -static-libgcc" for these options, which were overridden by our options (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67098).  This caused the bootstrapping gcc to dynamically link against libstdc++.

This wasn't a show-stopper problem in older gcc's before 5.0.  But the libstdc++ ABI changed with gcc 5.0, and we thus started seeing problems when building these newer gccs with older gccs.

**Comment by tgamblin** [comment]
@mplegendre: I was able to test this on `cab` and it works.  I compiled and ran hello world; works fine.  Thanks!
