### ISSUE TITLE
spack install llvm fails

### ISSUE THREAD

**Issue by srenatus** [scalability-llnl/spack#72]
Hi there.

Trying to use spack, I hit this road block:

```console
$ spack install llvm
==> Installing llvm
==> Trying to fetch from http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz
==> Staging archive: /home/jovyan/spack/var/spack/stage/llvm@3.5.1%gcc@4.9.2=unknown_arch/llvm-3.5.1.src.tar.xz
==> Created stage in /home/jovyan/spack/var/spack/stage/llvm@3.5.1%gcc@4.9.2=unknown_arch.
==> No patches needed for llvm.
==> Building llvm.
Traceback (most recent call last):
  File "/home/jovyan/spack/lib/spack/spack/build_environment.py", line 268, in fork
    function()
  File "/home/jovyan/spack/lib/spack/spack/package.py", line 833, in real_work
    self.install(self.spec, self.prefix)
  File "/home/jovyan/spack/var/spack/packages/llvm/package.py", line 52, in install
    *std_cmake_args)
TypeError: 'NoneType' object is not callable
==> Installing llvm
==> Trying to fetch from http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz
==> Staging archive: /home/jovyan/spack/var/spack/stage/llvm@3.5.1%gcc@4.9.2=unknown_arch/llvm-3.5.1.src.tar.xz
==> Created stage in /home/jovyan/spack/var/spack/stage/llvm@3.5.1%gcc@4.9.2=unknown_arch.
==> No patches needed for llvm.
```

[This is the dockerfile used to produce that problem.](https://gist.github.com/srenatus/690b0e8d89271bae21dd) Am I missing something?

Thanks for your help
Stephan

**Comment by tgamblin** [comment]
It's failing because it can't find the executable for cmake.  We talked a bit about the cryptic error message at the last telcon.  You can either install cmake via apt-get in your docker file, or you could just make the LLVM package depend_on('cmake'), and that should move this along a bit.  I have not tested this package on debian, but i don't see why it would fail.

Also, is this on master?  If master continues to be problematic, try the develop branch -- we're getting pretty close to a new release and I think the develop branch is actually more robust at the moment.

**Comment by srenatus** [comment]
Hi @tgamblin,

so there're two things I missed. Thanks for your hints.

Using both the develop branch and an installed cmake package, it's been building for 20 minutes now, so I supposet this issue is done.

Thanks again
Stephan

**Comment by tgamblin** [comment]
Sure thing.  I can make the spack package depend on cmake in the meantime.  We currently don't handle build dependencies as well as we probably should.
