### ISSUE TITLE
develop: compiler clang@unknown created for /usr/bin/clang-format

### ISSUE THREAD

**Issue by cuviper** [scalability-llnl/spack#95]
On Fedora 22 x86_64, I get a bogus `clang@unknown` compiler entry.

```
$ cat ~/.spack/compilers.yaml 
compilers:
  unknown_arch:
    clang@3.5.0:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: None
      fc: None
    clang@unknown:
      cc: /usr/bin/clang-format
      cxx: None
      f77: None
      fc: None
    gcc@5.1.1:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
```

But `clang-format` is just a code formatter, part of the same rpm that provided `clang@3.5.0`.

**Comment by tgamblin** [comment]
Hm.  The compiler search currently throws compilers with an unknown version into a common group, instead of lumping common versions together.  I think I initially wrote it this way to see which compilers had failed version checks, but it looks like the version check works fine, and the only things getting thrown in the "unknown" bin are commands that aren't compilers but match the regex.

I think the solution would be to require that compilers can pass the version check, and exclude them entirely if they don't.  Does that sound reasonable?

**Comment by cuviper** [comment]
I think that sounds fine to ignore those you can't fully identify, especially since it's possible to edit `compilers.yaml` manually to add weird things.

FWIW, I have 3 binaries that would match `clang-.*`: `clang-check`, `clang-format`, and `clang-tblgen`.  If I delete the unknown and try again, it looks like they're all indeed matching:

```
$ spack compiler add
==> Added 3 new compilers to /home/jistone/.spack/compilers.yaml
    clang@unknown  clang@unknown  clang@unknown
```

But only one entry is actually added.  I guess they're simply clobbering each other.

Anyway, I notice gcc is a little more nuanced with its suffix regex, otherwise things like `gcc-nm` would probably also cause issues.  Maybe clang should be refined too?

**Comment by tgamblin** [comment]
Fixed in develop.
